// Code generated by "stringer -type FilterMode"; DO NOT EDIT.

package tabPacket

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FilterModeRegex-0]
	_ = x[FilterModeContains-1]
}

const _FilterMode_name = "FilterModeRegexFilterModeContains"

var _FilterMode_index = [...]uint8{0, 15, 33}

func (i FilterMode) String() string {
	if i < 0 || i >= FilterMode(len(_FilterMode_index)-1) {
		return "FilterMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FilterMode_name[_FilterMode_index[i]:_FilterMode_index[i+1]]
}
