// Code generated by "stringer -type ViewType"; DO NOT EDIT.

package tabPacket

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ViewTypeContextHexPlain-0]
	_ = x[ViewTypeContextHex-1]
	_ = x[ViewTypeContextPlain-2]
	_ = x[ViewTypeContextBin-3]
	_ = x[ViewTypeHexdump-4]
	_ = x[ViewTypeAmountOverTime-5]
	_ = x[ViewTypeLengthOverTime-6]
}

const _ViewType_name = "ViewTypeContextHexPlainViewTypeContextHexViewTypeContextPlainViewTypeContextBinViewTypeHexdumpViewTypeAmountOverTimeViewTypeLengthOverTime"

var _ViewType_index = [...]uint8{0, 23, 41, 61, 79, 94, 116, 138}

func (i ViewType) String() string {
	if i < 0 || i >= ViewType(len(_ViewType_index)-1) {
		return "ViewType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ViewType_name[_ViewType_index[i]:_ViewType_index[i+1]]
}
