// Code generated by "stringer -type FilterParserResults"; DO NOT EDIT.

package packetui

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FilterParserResultsIgnore-0]
	_ = x[FilterParserResultsOnlyWithErrors-1]
	_ = x[FilterParserResultsOnlyWithResults-2]
}

const _FilterParserResults_name = "FilterParserResultsIgnoreFilterParserResultsOnlyWithErrorsFilterParserResultsOnlyWithResults"

var _FilterParserResults_index = [...]uint8{0, 25, 58, 92}

func (i FilterParserResults) String() string {
	if i < 0 || i >= FilterParserResults(len(_FilterParserResults_index)-1) {
		return "FilterParserResults(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FilterParserResults_name[_FilterParserResults_index[i]:_FilterParserResults_index[i+1]]
}
