// Code generated by "stringer -type FilterInput"; DO NOT EDIT.

package packetui

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FilterInputHex-0]
	_ = x[FilterInputBin-1]
	_ = x[FilterInputLiteral-2]
}

const _FilterInput_name = "FilterInputHexFilterInputBinFilterInputLiteral"

var _FilterInput_index = [...]uint8{0, 14, 28, 46}

func (i FilterInput) String() string {
	if i < 0 || i >= FilterInput(len(_FilterInput_index)-1) {
		return "FilterInput(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FilterInput_name[_FilterInput_index[i]:_FilterInput_index[i+1]]
}
